services:
  - type: web
    name: hear-this-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: '10000'
      - key: CORS_ORIGIN
        sync: false
        value: https://mobile-speaker-cj.vercel.app
      - key: ICE_SERVERS
        value: '[{"urls":"stun:stun.l.google.com:19302"},{"urls":"stun:stun1.l.google.com:19302"}]'
      - key: ROOM_EXPIRATION_MS
        value: '900000'
